test00.sh added

diff --git a/legit-add b/legit-add
--- a/legit-add
+++ b/legit-add
@@ -1,16 +1,16 @@
-#!/bin/dash
+#!/bin/bash
 
 # TODO
     # contain alpha-numeric characters plus '.', '-' and '_' characters.
 
 if [ $# -eq 0 ]; then
     echo "usage: legit-add <filenames>";
-    exit 0;
+    exit 1;
 fi
 
 if ! [ -d ".legit" ]; then
     echo "legit-add: error: no .legit directory containing legit repository exists";    # not $0
-    exit 0;
+    exit 1;
 fi
 
 index='.legit/index';
@@ -26,5 +26,6 @@ do
         cp "$i" "$index/$i"
     else
         echo "legit-add: error: can not open '$i'";
+        exit 1;     # TODO: delete if fail autotest
     fi
 done
diff --git a/legit-commit b/legit-commit
--- a/legit-commit
+++ b/legit-commit
@@ -1,8 +1,13 @@
-#!/bin/dash
+#!/bin/bash
 
 # TODO
 # catch err:
     # usage: legit-commit [-a] -m commit-message
+
+if [ ! -d '.legit' ]; then
+    echo "legit-commit: error: no .legit directory containing legit repository exists";
+    exit 1;
+fi
 
 all="0";
 msg="0";
@@ -25,7 +30,7 @@ done
 # echo "$all"; echo "$msg"; echo "$valid_msg";
 
 if [ $msg -eq "0" ] || [ $# -lt 2 ] || [ $valid_msg -eq "0" ]; then
-    echo "usage: legit-commit [-a] -m commit-message"; exit 0;
+    echo "usage: legit-commit [-a] -m commit-message"; exit 1;
 fi
 
 ####  -a  ####
@@ -78,7 +83,7 @@ fi
 
 # echo "$commit_flag";
 if [ "$commit_flag" -eq 0 ]; then
-    echo "nothing to commit"; exit 0;
+    echo "nothing to commit"; exit 1;
 fi
 
 ##### COMMIT_EDITMSG #####
