diary added

diff --git a/legit-rm b/legit-rm
--- a/legit-rm
+++ b/legit-rm
@@ -33,6 +33,16 @@ fi
 #done
 
 index='.legit/index';
+commit_num="0";                      # Get latest repo #
+msg_file='.legit/COMMIT_EDITMSG';
+# if [ -s $msg_file ]; then            # Not Empty
+#      commit_num=`cut -d' ' -f1 $msg_file`;
+# fi
+[ -s $msg_file ] && commit_num=`cut -d' ' -f1 $msg_file`;
+
+repo='.legit/logs/repo';
+snapshot="$repo/.snapshot.$commit_num";
+
 if [ $cached -eq "1" ] && [ $forced -eq "1" ]; then
     echo "--both";
     for i in "$@"
@@ -55,13 +65,41 @@ if [ $cached -eq "1" ] && [ $forced -eq "1" ]; then
         rm "$index/.index-e";
     done
 elif [ $cached -eq "1" ]; then
-    # echo "This only deletes from index";
+    # echo "HERE";
+    # ./legit-rm --cached a
+    # ./legit-rm --cached b
+    # # legit-rm: error: 'b' in index is different to both working file and repository
+    # ./legit-rm --cached c
+    # ./legit-rm --cached d
+    # ./legit-rm --cached e
+    # # legit-rm: error: 'e' is not in the legit repository
     for i in "$@"
     do
-        # echo "$i";
         if [ "$i" = "--cached" ] || [ "$i" = "--force" ] ; then
             continue;
-        elif [ -f "$index/$i" ]; then
+        fi
+
+        main_sha="0";
+        [ -f "$i" ] && main_sha=`shasum $i | cut -d' ' -f1`;
+
+        index_sha="0";
+        [ -f "$index/$i" ] && index_sha=`shasum "$index/$i" | cut -d' ' -f1`;
+
+        snap_sha="`grep "$i$" "$snapshot/.index" | cut -d' ' -f1`";
+        [ ! -n "$snap_sha" ] && snap_sha="0";
+
+        echo "main: $main_sha"; echo "index: $index_sha"; echo "repo: $snap_sha";
+
+        if [ "$main_sha" != "$index_sha" ] && [ "$index_sha" != "$snap_sha" ] && [ "$snap_sha" != "0" ]; then
+            echo "legit-rm: error: '$i' in index is different to both working file and repository";
+            exit 1;
+        elif [ -z $snap_sha ] && [ -z $index_sha ]; then
+            echo "legit-rm: error: '$i' is not in the legit repository";
+            exit 1;
+        fi
+        # exit 1;
+
+        if [ -f "$index/$i" ]; then
             # echo "deleting: $i | from: $index/$i";
             rm "$index/$i";
         else
@@ -71,34 +109,47 @@ elif [ $cached -eq "1" ]; then
         # cat "$index/.index";
         # echo "$i";
         # FOR LINUX
-        sed -i "/$i\$/d" "$index/.index"; # delete from status
+        # sed -i "/$i\$/d" "$index/.index"; # delete from status
 
         # FOR MAC
-        # sed -i -e "/$i\$/d" "$index/.index"; # delete from status
-        # rm "$index/.index-e";
+        sed -i -e "/$i\$/d" "$index/.index"; # delete from status
+        rm "$index/.index-e";
 
     done
 elif [ $forced -eq "1" ]; then
-    # echo "This deletes from main, index, and the status --> makes it untracked";
-
-
-
-    # echo "main: $main_sha";
-    # echo "index: $index_sha";
+    # echo "HERE";
+    # ./legit-rm --force a
+    # # legit-rm: error: 'a' is not in the legit repository
+    # ./legit-rm --force b
+    # ./legit-rm --force c
+    # # legit-rm: error: 'c' is not in the legit repository
+    # ./legit-rm --force d
+    # # legit-rm: error: 'd' is not in the legit repository
+    # ./legit-rm --force e
+    # # legit-rm: error: 'e' is not in the legit repository
     for i in "$@"
     do
-        main_sha="0";
-        if [ -f "$i" ]; then
-        main_sha=`shasum $i | cut -d' ' -f1`;
+        if [ "$i" = "--cached" ] || [ "$i" = "--force" ] ; then
+            continue;
         fi
 
+        main_sha="0";
+        [ -f "$i" ] && main_sha=`shasum $i | cut -d' ' -f1`;
+
         index_sha="0";
-        if [ -f "$index/$i" ]; then
-        index_sha=`shasum "$index/$i" | cut -d' ' -f1`;
+        [ -f "$index/$i" ] && index_sha=`shasum "$index/$i" | cut -d' ' -f1`;
+
+        snap_sha="`grep "$i$" "$snapshot/.index" | cut -d' ' -f1`";
+        [ -z "$snap_sha" ] && snap_sha="0";
+
+        echo "main: $main_sha"; echo "index: $index_sha"; echo "repo: $snap_sha";
+
+        if [ -z $snap_sha ] && [ -z $index_sha ]; then
+            echo "legit-rm: error: '$i' is not in the legit repository";
+            exit 1;
         fi
-        echo "main: $main_sha";
-        echo "index: $index_sha";
-    
+
+        # exit 1;
         # echo "$i";
         if [ "$i" = "--cached" ] || [ "$i" = "--force" ] ; then
             continue;
@@ -116,7 +167,7 @@ elif [ $forced -eq "1" ]; then
         # cat "$index/.index";
         # echo "$i";
         # FOR LINUX
-        sed -i "/\/$i\$/d" "$index/.index"; # delete from .index
+        # sed -i "/\/$i\$/d" "$index/.index"; # delete from .index
 
         # FOR MAC
         # sed -i -e "/\/$i\$/d" "$index/.index"; # delete from status
@@ -126,25 +177,64 @@ else
     # echo "This deletes from main and index --> makes it deleted";
     for i in "$@"
     do
+        main_sha="0";
+        # if [ -f "$i" ]; then
+        #     main_sha=`shasum $i | cut -d' ' -f1`;
+        # fi
+        [ -f "$i" ] && main_sha=`shasum $i | cut -d' ' -f1`;
+
+        index_sha="0";
+        # if [ -f "$index/$i" ]; then
+        #     index_sha=`shasum "$index/$i" | cut -d' ' -f1`;
+        # fi
+        [ -f "$index/$i" ] && index_sha=`shasum "$index/$i" | cut -d' ' -f1`;
+
+        snap_sha="`grep "$i$" "$snapshot/.index" | cut -d' ' -f1`";
+        # if [ ! -n "$snap_sha" ]; then
+        #     snap_sha="0";
+        # fi
+        [ -z "$snap_sha" ] && snap_sha="0";
+
+        # echo "main: $main_sha"; echo "index: $index_sha"; echo "repo: $snap_sha";
+
+        if [ "$main_sha" != "$index_sha" ] && [ "$index_sha" != "$snap_sha" ] && [ "$snap_sha" != "0" ]; then
+            echo "legit-rm: error: '$i' in index is different to both working file and repository";
+            exit 1;
+        elif [ "$main_sha" != "$index_sha" ] && [ "$index_sha" != "0" ]; then
+            echo "legit-rm: error: '$i' in repository is different to working file";
+            exit 1;
+        # elif [ "$main_sha" != "$index_sha" ] && [ "$index_sha" != "$snap_sha" ] && [ "$snap_sha" != "0" ]; then
+        #     echo "legit-rm: error: '$i' in index is different to both working file and repository";
+        #     exit 1;
+        elif [ "$main_sha" = "$index_sha" ] && [ "$index_sha" != "$snap_sha" ]; then
+            echo "legit-rm: error: '$i' has changes staged in the index";
+            exit 1;
+        elif [ -z $snap_sha ] && [ -z $index_sha ]; then
+            echo "legit-rm: error: '$i' is not in the legit repository";
+            exit 1;
+        fi
+
         # echo "$i";
         if [ "$i" = "--cached" ] || [ "$i" = "--force" ] ; then
             continue;
         fi
 
         if [ -f "$index/$i" ]; then     # delete from index
-            # echo "deleting: $i | from: $index/$i";
-            rm "$index/$i";
+            echo "deleting: $index/$i | from: $index/$i";
+            # rm "$index/$i";
         else
             echo "legit-rm: error: '$i' is not in the legit repository";
         fi
 
         # cat "$index/.index";
-        sed -i "/$i\$/d" "$index/.index"; # delete from .index
+        # sed -i "/$i\$/d" "$index/.index"; # delete from .index
 
         # sed -i -e "/$i$/d" "$index/.index"; # delete from status
         # rm "$index/.index-e";
+        # ff583f99fcc0d5193258f78ea3531d50c0e5d71b  .legit/logs/repo/.snapshot.2/a
 
-        rm "$i";    # delete from HEAD
+        echo "deleting: $i | from: $i";
+        # rm "$i";    # delete from HEAD
 
     done
 fi
@@ -193,44 +283,44 @@ fi
 # $ legit-commit -m "fourth commit"
 # Committed as commit 4
 
-$ legit-init
-Initialized empty legit repository in .legit
-$ echo 1 >a
-$ echo 2 >b
-$ echo 3 >c
-$ legit-add a b c
-$ legit-commit -m "first commit"
-Committed as commit 0
-$ echo 4 >>a
-$ echo 5 >>b
-$ echo 6 >>c
-$ echo 7 >d
-$ echo 8 >e
-$ legit-add b c d
-$ echo 9 >b
-$ legit-rm a
-legit-rm: error: 'a' in repository is different to working file
-$ legit-rm b
-legit-rm: error: 'b' in index is different to both working file and repository
-$ legit-rm c
-legit-rm: error: 'c' has changes staged in the index
-$ legit-rm d
-legit-rm: error: 'd' has changes staged in the index
-$ legit-rm e
-legit-rm: error: 'e' is not in the legit repository
-$ legit-rm --cached a
-$ legit-rm --cached b
-legit-rm: error: 'b' in index is different to both working file and repository
-$ legit-rm --cached c
-$ legit-rm --cached d
-$ legit-rm --cached e
-legit-rm: error: 'e' is not in the legit repository
-$ legit-rm --force a
-legit-rm: error: 'a' is not in the legit repository
-$ legit-rm --force b
-$ legit-rm --force c
-legit-rm: error: 'c' is not in the legit repository
-$ legit-rm --force d
-legit-rm: error: 'd' is not in the legit repository
-$ legit-rm --force e
-legit-rm: error: 'e' is not in the legit repository
+# ./legit-init
+# # Initialized empty legit repository in .legit
+# echo 1 >a
+# echo 2 >b
+# echo 3 >c
+# ./legit-add a b c
+# ./legit-commit -m "first commit"
+# # Committed as commit 0
+# echo 4 >>a
+# echo 5 >>b
+# echo 6 >>c
+# echo 7 >d
+# echo 8 >e
+# ./legit-add b c d
+# echo 9 >b
+# ./legit-rm a
+# # legit-rm: error: 'a' in repository is different to working file
+# ./legit-rm b
+# # legit-rm: error: 'b' in index is different to both working file and repository
+# ./legit-rm c
+# # legit-rm: error: 'c' has changes staged in the index
+# ./legit-rm d
+# # legit-rm: error: 'd' has changes staged in the index
+# ./legit-rm e
+# # legit-rm: error: 'e' is not in the legit repository
+# ./legit-rm --cached a
+# ./legit-rm --cached b
+# # legit-rm: error: 'b' in index is different to both working file and repository
+# ./legit-rm --cached c
+# ./legit-rm --cached d
+# ./legit-rm --cached e
+# # legit-rm: error: 'e' is not in the legit repository
+# ./legit-rm --force a
+# # legit-rm: error: 'a' is not in the legit repository
+# ./legit-rm --force b
+# ./legit-rm --force c
+# # legit-rm: error: 'c' is not in the legit repository
+# ./legit-rm --force d
+# # legit-rm: error: 'd' is not in the legit repository
+# ./legit-rm --force e
+# # legit-rm: error: 'e' is not in the legit repository
